# Infos du projet (depuis SonarCloud)
sonar.projectKey=chaima033_first-laravel-project
sonar.organization=chaima033
sonar.projectName=Laravel Todo App
sonar.projectVersion=1.0

# Dossiers à analyser
sonar.sources=app,routes,database
sonar.tests=tests

# Langage
sonar.language=php

# Rapport de couverture PHPUnit
sonar.php.coverage.reportPaths=coverage.xml

# Exclusions
sonar.exclusions=vendor/**,node_modules/**,public/**,storage/**,bootstrap/**

# Encodage
sonar.sourceEncoding=UTF-8

# URL SonarCloud
sonar.host.url=https://sonarcloud.io

# Token d'authentification
sonar.login=b2a9e1fc19351ad67307dc697132b61c794ae8c7
